// <auto-generated />
namespace ItemStock.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddAppUserEmail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAppUserEmail));
        
        string IMigrationMetadata.Id
        {
            get { return "201405270845509_AddAppUserEmail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
